const QueriesConstants = {
  QUERIES_RECEIVED: "QUERIES_RECEIVED",
  DASH_QUERIES_RECEIVED: "DASH_QUERIES_RECEIVED",
  DASH_QUERIES_OPTIONS_RECEIVED: "DASH_QUERIES_OPTIONS_RECEIVED"
};

module.exports = QueriesConstants;
